### ISSUE TITLE
Empty line before `}` throws non-descriptive error message

### ISSUE THREAD

**Issue by MaximilianJHuber** [piever/JuliaDBMeta.jl#33]
```
t = table((a=[1,2,3], b=[2,3,4]))

@groupby t :a {
    c = 1
}
```
is fine, but
```
t = table((a=[1,2,3], b=[2,3,4]))

@groupby t :a {
    c = 1

}
```
throws `syntax: { } matrix syntax is discontinued`. It is just very annoying to find an empty line being an issue.

**Comment by piever** [comment]
Thanks for reporting, the "multiline curly brackets" parse differently, so the macro was missing that case, should be fixed by #34
