### ISSUE TITLE
Allow JuliaDB 0.13.1

### ISSUE THREAD

**Issue by MaximilianJHuber** [piever/JuliaDBMeta.jl#43]
JuliaDB is set to `JuliaDB = "0.10, 0.11, 0.12"`, but `0.13.1` has been released.

**Comment by piever** [comment]
See #44 

I confess I don't really have a lot of bandwidth to maintain this package at the moment, and I don't use it anymore. Maybe it could make more sense to move it to JuliaData as well? CC: @andreasnoack @DilumAluthge

**Comment by DilumAluthge** [comment]
I'm not an owner of JuliaData, but I believe that @jpsamaroo is. You should be able to transfer to package to him, and then he'll be able to transfer it to JuliaData.

**Comment by jpsamaroo** [comment]
I'm not an owner of JuliaData, just a collaborator on JuliaDB.

**Comment by DilumAluthge** [comment]
Hmmm. In that case, maybe @viralbshah or @ararslan  can help us transfer this to JuliaData.

**Comment by ViralBShah** [comment]
I am not an owner of JuliaData either. @quinnj perhaps.

**Comment by ararslan** [comment]
I am an owner of JuliaData but do not have admin access on this repo.

**Comment by piever** [comment]
@ararslan I've invited you to collaborate to the repo. Does that give you enough privileges to move it to JuliaData?

**Comment by ararslan** [comment]
I don't believe so. I might be able to with administrative privileges (as opposed to "just" commit access) though I think the owner of the repo needs to transfer it. Do you not have the appropriate permissions in JuliaData? If not, I can set that up for you.

**Comment by piever** [comment]
Ah, I see. No, I don't have permissions to create repos in JuliaData, it'd be great if you could set those up for me.

**Comment by ararslan** [comment]
Okay, I've invited you to be an owner of JuliaData, so once you accept the invitation you can transfer the repository there.
